"""initial schema

Revision ID: e762a88f5f39
Revises: 
Create Date: 2026-09-10 10:21:37.430894
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'e762a88f5f39'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('topics', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('language', sa.Enum('en', 'hi', name='language'), nullable=False),
    sa.Column('style', sa.Enum('solo_anchor', 'two_host', name='episode_style'), nullable=False),
    sa.Column('github_login', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('email', name=op.f('uq_app_user_email'))
    )
    op.create_table('cluster',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('topics', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('centroid_item_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cluster'))
    )
    op.create_index('ix_cluster_run_date', 'cluster', ['run_date'], unique=False)
    op.create_table('source',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('api', 'rss', 'github', 'youtube', 'reddit', name='source_kind'), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('auth_ref', sa.String(length=64), nullable=True),
    sa.Column('poll_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('default_topics', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('trust_weight', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=32), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('trust_weight >= 0 AND trust_weight <= 1', name=op.f('ck_source_trust_weight_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source')),
    sa.UniqueConstraint('slug', name=op.f('uq_source_slug'))
    )
    op.create_index('ix_source_enabled_kind', 'source', ['enabled', 'kind'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('origin', sa.Text(), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_document_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document'))
    )
    op.create_table('episode',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('brief', 'knowledge', name='episode_mode'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'ready', 'failed', name='episode_status'), nullable=False),
    sa.Column('style', sa.Enum('solo_anchor', 'two_host', name='episode_style'), nullable=False),
    sa.Column('language', sa.Enum('en', 'hi', name='language'), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('audio_key', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('generation_seconds', sa.Float(), nullable=True),
    sa.Column('cost_inr', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_episode_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_episode'))
    )
    op.create_index('ix_episode_user_created', 'episode', ['user_id', 'created_at'], unique=False)
    op.create_table('ingest_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched', sa.Integer(), nullable=False),
    sa.Column('inserted', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_ingest_run_source_id_source'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingest_run'))
    )
    op.create_index('ix_ingest_run_source_started', 'ingest_run', ['source_id', 'started_at'], unique=False)
    op.create_table('item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=300), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('topics', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('engagement', sa.Float(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedded', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of_id', sa.UUID(), nullable=True),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], name=op.f('fk_item_cluster_id_cluster'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['item.id'], name=op.f('fk_item_duplicate_of_id_item'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name=op.f('fk_item_source_id_source'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item')),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_item_source_external')
    )
    op.create_index('ix_item_cluster_id', 'item', ['cluster_id'], unique=False)
    op.create_index('ix_item_embedded', 'item', ['embedded'], unique=False)
    op.create_index('ix_item_published_at', 'item', ['published_at'], unique=False)
    op.create_table('stack_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dependencies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('repos', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('starred_topics', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('recent_commit_terms', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_stack_profile_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stack_profile')),
    sa.UniqueConstraint('user_id', name=op.f('uq_stack_profile_user_id'))
    )
    op.create_table('claim',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('section', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_claim_document_id_document'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim'))
    )
    op.create_table('cost_entry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.String(length=48), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=96), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_inr', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('trace_id', sa.String(length=96), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], name=op.f('fk_cost_entry_episode_id_episode'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_entry'))
    )
    op.create_index('ix_cost_entry_created_at', 'cost_entry', ['created_at'], unique=False)
    op.create_index('ix_cost_entry_episode', 'cost_entry', ['episode_id'], unique=False)
    op.create_table('segment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('start_seconds', sa.Float(), nullable=True),
    sa.Column('end_seconds', sa.Float(), nullable=True),
    sa.Column('audio_key', sa.Text(), nullable=True),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], name=op.f('fk_segment_cluster_id_cluster'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], name=op.f('fk_segment_episode_id_episode'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_segment')),
    sa.UniqueConstraint('episode_id', 'position', name='uq_segment_episode_position')
    )
    op.create_table('claim_relation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_claim_id', sa.UUID(), nullable=False),
    sa.Column('target_claim_id', sa.UUID(), nullable=False),
    sa.Column('relation', sa.String(length=24), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source_claim_id <> target_claim_id', name=op.f('ck_claim_relation_no_self_relation')),
    sa.ForeignKeyConstraint(['source_claim_id'], ['claim.id'], name=op.f('fk_claim_relation_source_claim_id_claim'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_claim_id'], ['claim.id'], name=op.f('fk_claim_relation_target_claim_id_claim'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_relation')),
    sa.UniqueConstraint('source_claim_id', 'target_claim_id', 'relation', name='uq_claim_relation_edge')
    )
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('vote', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('vote IN (-1, 1)', name=op.f('ck_feedback_vote_is_thumb')),
    sa.ForeignKeyConstraint(['segment_id'], ['segment.id'], name=op.f('fk_feedback_segment_id_segment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_feedback_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback')),
    sa.UniqueConstraint('user_id', 'segment_id', name='uq_feedback_user_segment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('claim_relation')
    op.drop_table('segment')
    op.drop_index('ix_cost_entry_episode', table_name='cost_entry')
    op.drop_index('ix_cost_entry_created_at', table_name='cost_entry')
    op.drop_table('cost_entry')
    op.drop_table('claim')
    op.drop_table('stack_profile')
    op.drop_index('ix_item_published_at', table_name='item')
    op.drop_index('ix_item_embedded', table_name='item')
    op.drop_index('ix_item_cluster_id', table_name='item')
    op.drop_table('item')
    op.drop_index('ix_ingest_run_source_started', table_name='ingest_run')
    op.drop_table('ingest_run')
    op.drop_index('ix_episode_user_created', table_name='episode')
    op.drop_table('episode')
    op.drop_table('document')
    op.drop_index('ix_source_enabled_kind', table_name='source')
    op.drop_table('source')
    op.drop_index('ix_cluster_run_date', table_name='cluster')
    op.drop_table('cluster')
    op.drop_table('app_user')
    # ### end Alembic commands ###
